spring:
  application:
    name: doosanMig
  profiles:
    active: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:sqlserver://localhost:1433;DatabaseName=doosanMig;sslProtocol=TLSv1.2;encrypt=true;trustServerCertificate=true"
    username: sa
    password: Megazone@134
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
external:
  serviceNOW:
    authID : "admin"
    authPWD : "S=laAJ12*ooJ"
    apiURL : "https://dev120528.service-now.com/api/now"
